title: Global Knowledge Sharing Platform for Patient Safety (GKPS)
url: https://www.gkps.net
favicon: /images/gkpslogo2.png
colors:
  primary-color: "#0559c1"
  secondary-color: "#0559b9"
  media-colors:
    - title: media-color-one
      color: "#9f9e9e"
    - title: media-color-two
      color: "#938e8e"
    - title: media-color-three
      color: "#00838f"
    - title: media-color-four
      color: "#00838f"
    - title: media-color-five
      color: "#00838f"
description: ""
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d2qijbsoh0q7ha.amplifyapp.com
prod: https://master.d2qijbsoh0q7ha.amplifyapp.com
resources_name: patient-safety-networks
shareicon: /images/gkpslogo2.png
is_government: false
facebook-pixel: ""
google_analytics: ""
google_analytics_ga4: ""
linkedin-insights: ""
